language: python

sudo: required
dist: xenial
services:
  - docker

env:
  - CHANGE_MINIKUBE_NONE_USER=true

before_script:
  - pip install --upgrade awscli
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
  - curl -o aws-iam-authenticator.sha256 https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator.sha256
  - diff <(sha256sum aws-iam-authenticator | awk '{print $1}') <(cat aws-iam-authenticator.sha256 | awk '{print $1}')
  - chmod +x ./aws-iam-authenticator
  - cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
  - chmod 700 get_helm.sh
  - sudo ./get_helm.sh

script:
  - aws eks --region ap-northeast-1 update-kubeconfig --name david-test
  - kubectl get pods
  - docker build -t davidh83110/jupyter-k8s-singleuser-javascript jupyterhub/ -f jupyterhub/Dockerfile_singleuser
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWD"
  - docker push davidh83110/jupyter-k8s-singleuser-javascript:latest
  - helm init --service-account tiller --wait || travis_terminate 1;
  - helm upgrade --values jupyterhub/config.yaml david-jhub jupyterhub || travis_terminate 1;
  - kubectl apply -f mysql/mysql-deployment.yaml || travis_terminate 1;
