language: python

sudo: required
dist: xenial
services:
  - docker

env:
  - CHANGE_MINIKUBE_NONE_USER=true

# before_install:
#   - go get -u github.com/kardianos/govendor

before_script:
  - sudo mount --make-rshared /
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/v0.28.1/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  - sudo minikube -v 9 start --vm-driver=none --bootstrapper=kubeadm --kubernetes-version=v1.10.0 --extra-config=apiserver.authorization-mode=RBAC
  - minikube update-context
  - until kubectl get nodes minikube | grep " Ready";do kubectl get nodes; sleep 1; done
  - until kubectl -n kube-system get pods -lk8s-app=kube-dns -o jsonpath="{.items[0].status.phase}" | grep "Running" ;do sleep 1;echo "waiting for kube-addon-manager to be available"; kubectl get pods --all-namespaces; done
  - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
  - curl -o aws-iam-authenticator.sha256 https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator.sha256
  - diff <(sha256sum aws-iam-authenticator | awk '{print $1}') <(cat aws-iam-authenticator.sha256 | awk '{print $1}')
  - chmod +x ./aws-iam-authenticator
  - cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator

script:
  - aws eks --region ap-northeast-1 update-kubeconfig --name david-test
  - kubectl get pods
  - docker build -t davidh83110/jupyter-k8s-singleuser-javascript jupyterhub/ -f jupyterhub/Dockerfile_singleuser
  - helm init --service-account tiller --wait
  - helm upgrade --values jupyterhub/config.yaml david-jhub jupyterhub
  - kubectl apply -f mysql/mysql-deployment.yaml
  